apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 30m
  path: clusters/main/kubernetes/system/system-upgrade-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

