---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
  namespace: it-tools
spec:
  interval: 15m
  chart:
    spec:
      chart: it-tools
      version: 8.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    resources:
      requests:
        cpu: 10m
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: it-tools.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: "Developer"
            widget:
              enabled: false
          traefik:
            enabled: false
