---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: peanut
  namespace: peanut
spec:
  interval: 15m
  chart:
    spec:
      chart: peanut
      version: 8.7.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    resources:
      requests:
        cpu: 10m
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: peanut.${BASE_DOMAIN}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: "cloudflare-prod"
          homepage:
            enabled: false
          traefik:
            enabled: false
    persistence:
      config:
        enabled: true
        volsync:
          - name: config
            credentials: backblaze
            type: restic
            dest:
              enabled: false # change to true on restore
            src:
              enabled: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                WEB_PORT: '{{ .Values.service.main.ports.main.port }}'
