---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: myspeed
  namespace: myspeed
spec:
  interval: 15m
  chart:
    spec:
      chart: myspeed
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: myspeed.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: "Network - Performance"
            widget:
              type: "myspeed"
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: allowlist-private
                namespace: "traefik"
    persistence:
      data:
        volsync:
          - name: data-1
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true