apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterissuer
  namespace: flux-system
spec:
  interval: 30m
  path: clusters/main/kubernetes/core/clusterissuer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

