---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 7.3.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    resources:
      requests:
        cpu: 10m
    externaldns:
      interval: 10m
      logFormat: text
      logLevel: info
      piholePassword: "${PIHOLE_PASSWORD}"
      piholeServer: "http://10.242.1.4"
      piholeAPIVersion: "6" # set to 6 for pi-hole v6
      domainFilters:
        - "${BASE_DOMAIN}"
        - "${BASE_DOMAIN_EXT}"
        - "${SHLINK_DOMAIN_EXT}"
      policy: upsert-only
      provider: pihole
      registry: noop
      sources:
        - ingress
      # - service
    podOptions:
      hostUsers: true