---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    externaldns:
      interval: 10m
      logFormat: text
      logLevel: info
      piholePassword: "${PIHOLE_PASSWORD}"
      piholeServer: "${PIHOLE_SERVER}"
      domainFilters:
        - "${BASE_DOMAIN}"
        - "${BASE_DOMAIN_EXT}"
      policy: upsert-only
      provider: pihole
      registry: noop
      sources:
        - ingress
      # - service
#   workload:   # upcoming unreleased change in upstream added 2025-04-02
#     main:
#        podSpec:
#         containers:
#           main:
#             env:
#               EXTERNAL_DNS_PIHOLE_API_VERSION: # Default is 5. Eligible values are 5 or 6. #
