apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nebula-sync
  namespace: flux-system
spec:
  interval: 30m
  path: clusters/main/kubernetes/apps/nebula-sync/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster