apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: prometheus-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-operator
      version: 11.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    kps:
      crds:
        enabled: true
        upgradeJob:
          enabled: true
          forceConflicts: true
      prometheusOperator:
        enabled: false
      global:
        rbac:
          create: false
      grafana:
        enabled: false
        forceDeployDashboards: true
        defaultDashboardsEnabled: true
        forceDeployDatasources: true