---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: ntfy
spec:
  interval: 15m
  chart:
    spec:
      chart: ntfy
      version: 11.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 10m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false # change to 'true' to stop all pods whenever world maintenance is needed
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: ntfy.${BASE_DOMAIN_EXT} # update NTFY_BASE_URL
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: false
          traefik:
            enabled: true
            entrypoints:
              - websecure
    persistence:
      config:
        enabled: true
        volsync:
          - name: config
            credentials: backblaze
            type: restic
            dest:
              enabled: false # enable on restore
            src:
              enabled: true
    service:
      main:
        enabled: true
        loadBalancerIP: "${NTFY_IP}"
        type: LoadBalancer
        ports:
          smtp:
            enabled: true
            targetSelector: main
            port: 25
            protocol: http
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                NTFY_BASE_URL: "https://ntfy.${BASE_DOMAIN_EXT}"
                NTFY_BEHIND_PROXY: true
                ENABLE_CACHE_FILE: true
                ENABLE_AUTH_FILE: true
                NTFY_VISITOR_SUBSCRIPTION_LIMIT: 100
                NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
                NTFY_SMTP_SERVER_LISTEN: ":25"
                NTFY_SMTP_SERVER_DOMAIN: "ntfy.${BASE_DOMAIN_EXT}"
                NTFY_ENABLE_SIGNUP: false
                NTFY_ENABLE_LOGIN: true