apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
spec:
  interval: 30m
  path: clusters/main/kubernetes/system/snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

