apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-gpu-plugin-operator
  namespace: flux-system
spec:
  interval: 30m
  path: clusters/main/kubernetes/core/intel-gpu-plugin-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

