---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nebula-sync
  namespace: nebula-sync
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    image:
      repository: ghcr.io/lovelaze/nebula-sync
      pullPolicy: IfNotPresent
      tag: v0.8.0@sha256:e1d1546d337c894ac430510aaf5d9c6116df675b567bebbcc283fd882fe0fbf2
    service:
      main:
        enabled: false
        ports:
          main:
            enabled: false
    portal:
      open:
        enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PRIMARY: "https://10.242.1.4|password"
                REPLICAS: "https://10.242.1.6|password"
                FULL_SYNC: false # if set to false, enable and select keys below
                RUN_GRAVITY: false
                CRON: "*/15 * * * *"
                CLIENT_SKIP_TLS_VERIFICATION: true
                # Enable keys below for granular control over sync
                SYNC_CONFIG_DNS: true
                SYNC_CONFIG_DHCP: false
                SYNC_CONFIG_NTP: false
                SYNC_CONFIG_RESOLVER: false
                SYNC_CONFIG_DATABASE: false
                SYNC_CONFIG_MISC: false
                SYNC_CONFIG_DEBUG: false
                SYNC_GRAVITY_DHCP_LEASES: false
                SYNC_GRAVITY_GROUP: true
                SYNC_GRAVITY_AD_LIST: true
                SYNC_GRAVITY_AD_LIST_BY_GROUP: true
                SYNC_GRAVITY_DOMAIN_LIST: true
                SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: true
                SYNC_GRAVITY_CLIENT: true
                SYNC_GRAVITY_CLIENT_BY_GROUP: true
              # No service ports so disable probes
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false