---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nebula-sync
  namespace: nebula-sync
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.1.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    resources:
      requests:
        cpu: 25m
    podOptions:
      hostUsers: true
    image:
      repository: ghcr.io/lovelaze/nebula-sync
      pullPolicy: IfNotPresent
      tag: v0.11.0@sha256:17177eb65637d73eee7169a789e69eda8395d4d4398cc0cd08e2cbeb7c2910f1
    service:
      main:
        enabled: false
        ports:
          main:
            enabled: false
    portal:
      open:
        enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PRIMARY: "https://${PIHOLE_1_HOST}|${PIHOLE_1_PASSWORD}"
                REPLICAS: "https://${PIHOLE_2_HOST}|${PIHOLE_2_PASSWORD}"
                FULL_SYNC: false # if set to false, enable and select keys below
                RUN_GRAVITY: false
                CRON: "*/15 * * * *"
                CLIENT_SKIP_TLS_VERIFICATION: true
                # Enable keys below for granular control over sync
                SYNC_CONFIG_DNS: true
                SYNC_CONFIG_DHCP: false
                SYNC_CONFIG_NTP: false
                SYNC_CONFIG_RESOLVER: false
                SYNC_CONFIG_DATABASE: false
                SYNC_CONFIG_MISC: false
                SYNC_CONFIG_DEBUG: false
                SYNC_GRAVITY_DHCP_LEASES: false
                SYNC_GRAVITY_GROUP: true
                SYNC_GRAVITY_AD_LIST: true
                SYNC_GRAVITY_AD_LIST_BY_GROUP: true
                SYNC_GRAVITY_DOMAIN_LIST: true
                SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: true
                SYNC_GRAVITY_CLIENT: true
                SYNC_GRAVITY_CLIENT_BY_GROUP: true
              # No service ports so disable probes
              probes:
                liveness:
                  enabled: true
                  type: exec
                  command:
                    - nebula-sync
                    - healthcheck
                  spec:
                    initialDelaySeconds: 10
                    periodSeconds: 3
                readiness:
                  enabled: false
                startup:
                  enabled: false