---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-bedrock
  namespace: minecraft-bedrock
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft-bedrock
      version: 10.5.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false # change to 'true' to stop all pods whenever world maintenance is needed
    image:
      repository: docker.io/itzg/minecraft-bedrock-server
      tag: 2024.11.0@sha256:f488814fe5d9cfea27d1dda93598d3f5970845bddcdef86c183bbccbbae381be
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"  
    persistence:
      config:
        enabled: true
        volsync:
          - name: config-1
            credentials: backblaze
            type: restic
            dest:
              enabled: true
            src:
              enabled: true
      worlds:
        enabled: true
        path: "/mnt/pool1/minecraft-bedrock/minecraft-bedrock-worlds"
        server: "${PLUTO_IP}"
        type: nfs
        mountPath: "/data/worlds"
    service:
      main:
        enabled: true
        loadBalancerIP: "${MINECRAFT_IP}"
        type: LoadBalancer
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                # renovate: datasource=custom.minecraft-bedrock depName=minecraft-bedrock
                VERSION: 1.21.70.04
                ALLOW_CHEATS: true
                DIFFICULTY: peaceful
                GAMEMODE: creative
                LEVEL_NAME: 71YC-Server
                ONLINE_MODE: true
                OPS: "${MINECRAFT_OPS}"
                SERVER_NAME: 71YC Server
                TEXTUREPACK_REQUIRED: true
                VIEW_DISTANCE: 64
                ALLOW_LIST: true