apiVersion: v1
kind: Namespace
metadata:
    name: shlink-web-client
    labels:
        pod-security.kubernetes.io/enforce: privileged
    annotations:
        volsync.backube/privileged-movers: "true"