---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 15m
  chart:
    spec:
      chart: gatus
      version: 2.11.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 10m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    resources:
      requests:
        cpu: 10m
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: gatus.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: "Monitoring"
            widget:
              enabled: enabled
          traefik:
            enabled: false
    cnpg:
      main:
        cluster:
          singleNode: true
        mode: standalone # change to `recovery` on restore
        backups:
          enabled: true
          credentials: backblaze
          retentionPolicy: "14d"
        recovery:
          credentials: backblaze
    configmap:
      config:
        enabled: true
        data:
          config.yaml: |
            {{- if .Values.cnpg.main.enabled }}
            storage:
              type: postgres
              path: {{ (printf "%s?client_encoding=utf8" (.Values.cnpg.main.creds.std | trimAll "\"")) | quote }}
            {{- end }}

            alerting:
              ntfy:
                topic: gatus-updates
                token: ${NTFY_TOKEN_GATUS}
                default-alert:
                  failure-threshold: 1
                  success-threshold: 1
                  send-on-resolved: true
                  description: "healthcheck failed"
            
            endpoints:
              - name: musson.uk
                group: websites
                url: https://musson.uk
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY] == pat(*James Musson*)"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: muss.uk
                group: websites
                url: https://muss.uk
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: minecraft-download-links
                group: games
                url: https://net-secondary.web.minecraft-services.net/api/v1.0/download/links
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "has([BODY].result.links) == true"
                alerts:
                  - type: ntfy
              - name: minecraft-bedrock
                group: games
                url: udp://mc.${BASE_DOMAIN_EXT}:19132
                interval: 5m
                conditions:
                  - "[CONNECTED] == true"
                alerts:
                  - type: ntfy
              - name: jellyfin
                group: media
                url: https://jellyfin.${BASE_DOMAIN}/health
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY] == Healthy"
                alerts:
                  - type: ntfy
              - name: scrutiny
                group: pluto
                url: https://scrutiny.musson-lan.uk/api/health
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY].success == true"
                alerts:
                  - type: ntfy

            connectivity:
              checker:
                target: 1.1.1.1:53
                interval: 60s