---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 15m
  chart:
    spec:
      chart: gatus
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 10m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    resources:
      requests:
        cpu: 10m
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: gatus.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: "Monitoring"
            widget:
              enabled: enabled
          traefik:
            enabled: false
    cnpg:
      main:
        enabled: true
        cluster:
          singleNode: true
        mode: recovery # change to `recovery` on restore
        backups:
          enabled: true
          credentials: backblaze
          retentionPolicy: "14d"
        recovery:
          credentials: backblaze