---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 15m
  chart:
    spec:
      chart: gatus
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 10m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    resources:
      requests:
        cpu: 10m
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: gatus.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: "Monitoring"
            widget:
              enabled: enabled
          traefik:
            enabled: false
    cnpg:
      main:
        enabled: true
        cluster:
          singleNode: true
        mode: standalone # change to `recovery` on restore
        backups:
          enabled: true
          credentials: backblaze
          retentionPolicy: "14d"
        recovery:
          credentials: backblaze
    configmap:
      config:
        enabled: true
        data:
          config.yaml: |
            {{- if .Values.cnpg.main.enabled }}
            storage:
              type: postgres
              path: {{ (printf "%s?client_encoding=utf8" ( .Values.cnpg.main.creds.std | trimAll "\"")) | quote }}
            {{- end }}

            ui:
              logo: "https://musson.uk/favicon.png"
              buttons:
                - name: homepage
                  link: "https://homepage.${BASE_DOMAIN}"
              default-sort-by: group

            alerting:
              ntfy:
                url: "https://ntfy.${BASE_DOMAIN_EXT}"
                topic: "gatus-updates"
                token: "${NTFY_TOKEN_GATUS}"
                priority: 5
                default-alert:
                  failure-threshold: 1
                  success-threshold: 1
                  send-on-resolved: true
              email:
                from: "${GATUS_EMAIL_HOST_USER}"
                username: "${GATUS_EMAIL_HOST_USER}"
                password: "${GATUS_EMAIL_HOST_PASSWORD}"
                host: "${SMTP_SERVER}"
                port: ${SMTP_PORT}
                to: "${EMAIL1}"
                default-alert:
                  failure-threshold: 1
                  success-threshold: 1
                  send-on-resolved: true
            
            endpoints:
              - name: musson.uk
                group: websites
                url: "https://musson.uk"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY] == pat(*James Musson*)"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy