---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 15m
  chart:
    spec:
      chart: gatus
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 10m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    resources:
      requests:
        cpu: 10m
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: gatus.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: "Monitoring"
            widget:
              enabled: enabled
          traefik:
            enabled: false
    cnpg:
      main:
        cluster:
          singleNode: true
        mode: standalone # change to `recovery` on restore
        backups:
          enabled: true
          credentials: backblaze
          retentionPolicy: "14d"
        recovery:
          credentials: backblaze
    configmap:
      config:
        enabled: true
        data:
          config.yaml: |
            {{- if .Values.cnpg.main.enabled }}
            storage:
              type: postgres
              path: {{ (printf "%s?client_encoding=utf8" (.Values.cnpg.main.creds.std | trimAll "\"")) | quote }}
            {{- end }}

            ui:
              logo: "https://musson.uk/favicon.png"
              buttons:
                - name: homepage
                  link: "https://homepage.${BASE_DOMAIN}"
              default-sort-by: group

            alerting:
              ntfy:
                url: "https://ntfy.${BASE_DOMAIN_EXT}"
                topic: "gatus-updates"
                token: "${NTFY_TOKEN_GATUS}"
                priority: 5
                default-alert:
                  failure-threshold: 1
                  success-threshold: 1
                  send-on-resolved: true
              email:
                from: "gatus@${SMTP_HOST_DOMAIN}"
                username: "gatus@{SMTP_HOST_DOMAIN}"
                password: ""
                host: "${SMTP_SERVER}"
                port: "${SMTP_PORT}"
                to: "${EMAIL1}"
                default-alert:
                  failure-threshold: 1
                  success-threshold: 1
                  send-on-resolved: true
            
            endpoints:
              - name: musson.uk
                group: websites
                url: "https://musson.uk"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY] == pat(*James Musson*)"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: muss.uk
                group: websites
                url: "https://muss.uk"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: minecraft-download-links
                group: websites
                url: "https://net-secondary.web.minecraft-services.net/api/v1.0/download/links"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "has([BODY].result.links) == true"
                alerts:
                  - type: ntfy
              - name: minecraft-bedrock
                group: apps-hydra
                url: "udp://mc.${BASE_DOMAIN_EXT}:19132"
                interval: 5m
                conditions:
                  - "[CONNECTED] == true"
                alerts:
                  - type: ntfy
              - name: jellyfin
                group: apps-hydra
                url: "https://jellyfin.${BASE_DOMAIN}/health"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY] == Healthy"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: scrutiny
                group: apps-pluto
                url: "https://scrutiny.musson-lan.uk/api/health"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY].success == true"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: shlink
                group: apps-hydra
                url: "https://muss.uk/rest/health"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY].status == pass"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: nebula-sync
                group: apps-hydra
                url: "https://nebula-sync.musson-lan.uk/health"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: pihole-dns
                group: dns
                url: "10.242.1.53:53"
                dns:
                  query-name: "d.root-servers.net"
                  query-type: "A"
                conditions:
                  - "[CONNECTED] == true"
                  - "[DNS_RCODE] == NOERROR"
                alerts:
                  - type: ntfy
              - name: pihole-valledan-dns
                group: dns
                url: "10.242.1.4:53"
                dns:
                  query-name: "l.root-servers.net"
                  query-type: "A"
                conditions:
                  - "[CONNECTED] == true"
                  - "[DNS_RCODE] == NOERROR"
                alerts:
                  - type: ntfy
              - name: pihole-kindath-dns
                group: dns
                url: "10.242.1.6:53"
                dns:
                  query-name: "k.root-servers.net"
                  query-type: "A"
                conditions:
                  - "[CONNECTED] == true"
                  - "[DNS_RCODE] == NOERROR"
                alerts:
                  - type: ntfy
                    failure-threshold: 2
              - name: pihole-valledan-web
                group: dns
                url: "https://valledan.musson-lan.uk/api/info/login"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY].dns == true"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: pihole-kindath-web
                group: dns
                url: "https://kindath.musson-lan.uk/api/info/login"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[BODY].dns == true"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: nut-pluto
                group: ups
                url: "tcp://10.242.1.242:3493"
                interval: 5m
                conditions:
                  - "[CONNECTED] == true"
                alerts:
                  - type: ntfy
              - name: nut-valledan
                group: ups
                url: "tcp://10.242.1.4:3493"
                interval: 5m
                conditions:
                  - "[CONNECTED] == true"
                alerts:
                  - type: ntfy
              - name: pluto-web
                group: pluto
                url: "https://pluto.${BASE_DOMAIN}"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy
              - name: kerberos-web
                group: pluto
                url: "https://kerberos.${BASE_DOMAIN}"
                interval: 5m
                conditions:
                  - "[STATUS] == 200"
                  - "[CERTIFICATE_EXPIRATION] > 48h"
                alerts:
                  - type: ntfy

            connectivity:
              checker:
                target: 1.1.1.1:53
                interval: 60s

            maintenance:
              start: 00:00
              duration: 6h
              timezone: "Europe/London"