apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-operator
  namespace: flux-system
spec:
  interval: 30m
  path: clusters/main/kubernetes/kube-system/intel-device-plugins-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster