---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: streammaster
  namespace: streammaster
spec:
  interval: 15m
  chart:
    spec:
      chart: streammaster
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 10m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    resources:
      requests:
        cpu: 10m
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        name: backblaze
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: streammaster.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: "Ripping"
            widget:
              enabled: false
          traefik:
            enabled: false
    cnpg:
      main:
        cluster:
          singleNode: true
        mode: recovery # change to `recovery` on restore
        backups:
          enabled: true
          credentials: backblaze
          retentionPolicy: "14d"
        recovery:
          credentials: backblaze
    persistence:
      config:
        enabled: true
        volsync:
          - name: config
            credentials: backblaze
            type: restic
            dest:
              enabled: true # change to true on restore
              cacheCapacity: 10Gi
            src:
              enabled: true
              cacheCapacity: 10Gi