---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 21.3.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      backblaze:
        accessKey: "${B2_ACCESSKEY}"
        bucket: "${B2_BUCKET}"
        encrKey: "${B2_ENCRKEY}"
        secretKey: "${B2_SECRETKEY}"
        type: s3
        url: "${B2_URL}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: jellyfin.${BASE_DOMAIN}
        integrations:
          certManager:
            certificateIssuer: cloudflare-prod
            enabled: true
          homepage:
            enabled: true
            group: Media
            widget:
              custom:
                key: "${JELLYFIN_API_KEY}"
              customkv:
                - key: enableBlocks
                  value: "true"
                - key: enableMediaControl
                  value: "false"
                - key: enableUser
                  value: "true"
                - key: showEpisodeNumber
                  value: "true"
                - key: expandOneStreamToTwoRows
                  value: "false"
              enabled: true
          traefik:
            enabled: false
    persistence:
      config:
        enabled: true
        mountPath: "/config"
        volsync:
          - name: config-3
            credentials: backblaze
            type: restic
            dest:
              enabled: false # ensure this is set to "true" before attempting restore
            src:
              enabled: true
              trigger:
                schedule: 30 0 * * *
      movies:
        enabled: true
        mountPath: "/mnt/movies"
        path: "/mnt/pool0/movies"
        server: "${PLUTO_IP}"
        readOnly: false
        type: nfs 
    workload:
      main:
        podSpec:      
          containers:
            main:
              resources:
                limits:
                  gpu.intel.com/i915: 1
                  memory: 5Gi
                requests:
                  gpu.intel.com/i915: 1
                  cpu: 50m